---
title: "BCMRmd Report v0.1"
author: "Alex Saltzman"
date: "`r Sys.Date()`"
tidy: formatR
output:
  html_document:
    code_folding: hide
    highlight:  # pygments, kate, monochrome, zenburn
    toc: yes
    includes:
      #in_header: header.html 
      in_header:
mainfont: Noto Sans
params:
  paramfile:
    value:
  ROOTPATH:
    #value: "`normalizePath(dirname('.'))`"
    value: "../.."
    description: supposed to be dynamic
  routines:
    value:
      tackle: true 
      E2G: false
      MASIC: false
      denovo: false
  MASIC:
      value:
        ROOTPATH:
          value: "../../"
  E2G:
    value:
      ANOTHER:
        value: 1
  tackle:
    value:
      ROOTPATH:
          value: "../.."
      cluster_methods:
          value: [kmeans]
      cluster:
        value:
          cluster_rows:
            value: true
            description: "cluster the rows"
          cluster_columns:
            value: true
          cluster_row_slices:
            value: true
          cluster_col_slices:
            value: true
          clustering_distance_rows:
            value: euclidean
          clustering_method_rows:
            value: ward.d2
          legend_include:
            value: 
            description: "metadata variables to include"
          legend_exclude:
            value:
            description: "metadata variables to exclude"
        pca:
          value:
            color:
              value: "treat"
            marker:
              value: "geno"
            annotate:
              value: true
            max_pc:
              value: 4
  test:
    value:
      a:
        value: 1
        type: int
      b:
        value: 2
  logging:
    value:
      message: FALSE
      warning: FALSE
---

# index
```{r index_setup, include=TRUE}
suppressPackageStartupMessages(library(cmapR))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(fs))
suppressPackageStartupMessages(library(limma))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(circlize))
suppressPackageStartupMessages(library(tidymodels))
suppressPackageStartupMessages(library(tidymodels))
suppressPackageStartupMessages(library(tibble))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(yaml))
```

load local params

```{r, label=local-params}
# print(parmas)
knitr::opts_chunk$set(root.dir = normalizePath("."))
knitr::opts_chunk$set(message = params$logging$message, warning = params$logging$warning)
knitr::opts_chunk$set(echo = TRUE)


.f <- "PARAMS.yaml"
if (fs::file_exists(.f)) {
  local_params <- yaml::yaml.load_file(.f)
  params <- modifyList(params, local_params)
}
# print(params)
```



```{r index_settings}
BCMBLUE <- "#002396"
knitr::knit_hooks$set(debug = function(before, options, envir) {
  if (!before) {
    message(
      paste(names(envir), as.list(envir),
        sep = " = ", collapse = "\n"
      )
    )
  }
})
```



# MASIC
```{r, label=index-render-masic, results='hide', eval=params$routines$MASIC, include=params$routines$MASIC}

.new_params <- params$MASIC
.new_params$logging <- params$logging

rmarkdown::render("MASIC.Rmd",
  output_file = "MASIC.html",
  quiet = T,
  params = .new_params,
  envir = new.env(),
)
# knitr::knit_child('MASIC.Rmd')
```
[MASIC](MASIC.html)


# E2G
```{r, label=E2G, results='show', eval=params$routines$E2G, include=params$routines$E2G}
# print(params$E2G)
# print(params$E2G$value$ANOTHER)
.new_params <- params$E2G
.new_params$logging <- params$logging
.out <- rmarkdown::render("E2G.Rmd",
  output_file = "E2G.html",
  params = .new_params,
  envir = new.env(),
  quiet = T,
)
# #knitr::knit_child('MASIC.Rmd')
# htmltools::includeHTML(.out)
```


# tackle
```{r, label=tackle, results='show', message=params$logging$message, warning=params$logging$warning,   eval=params$routines$tackle}
# .params<-params$tackle
# cat(as.character(params$tackle))

.new_params <- params$tackle
.new_params$logging <- params$logging
.out <- rmarkdown::render("tackle.Rmd",
  output_file = "tackle.html",
  params = params$tackle,
  envir = new.env(),
  quiet = T
) # , params=.params)

# print(.out)
.dirname <- normalizePath(dirname(".out"))
(.dirname)
```
```{r, label=index-blank123}
# rint(normalizePath(dirname('.')) )
# rmarkdown::render('tackle.Rmd', output_file = 'tackle.html', params=params)
# render_cluster_report <- function(){
#   .output_file_name <- paste0("cluster_", "method_", method, ".html")
#   rmarkdown::render("cluster.Rmd",
#               output_file=.output_file_name,
#               params=list()
#               #params=.params,
#               #envir = globalenv(),
#               #envir = new_env
#               #documentation=1,
#               )
#   return(.output_file_name)
# .out %>% htmltools::includeHTML()
# fs::path_join(c("../", .out)) %>%  htmltools::includeHTML()
```

LINK
```{r tackle-link, echo=F, results="asis"}
.out <- fs::path_rel(.out)
.html <- cat(paste0("[", .out, "](", .out, ")"), "\n\n")
print(.html)
## {-}
```


# denovo
```{r, label=denovo, results='hide', eval=F}
rmarkdown::render("denovo.Rmd",
  output_file = "denovo.html",
  quiet = T
)
```
[denvo](denovo.html)

