---
title: "MASIC"
author: "Alex Saltzman"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn # pygments, kate, monochrome, zenburn
#output: html_document:
#  code

params:
  subtitle: "<subtitle>"
  ROOTPATH: ".."
  #ROOTPATH: "`r fs::path_wd('.')`"
  logging:
    value:
      message: FALSE
      warning: FALSE
---


```{r, label=masic-front}
knitr::opts_chunk$set(message = params$logging$MESSAGE)
knitr::opts_chunk$set(warning = params$logging$WARNING)
  
#ROOTPATH<- "./testdata"
library(fs)
library(dplyr)
library(tidyr)
library(purrr)
library(vroom)
library(dplyr)
library(knitr)
library(tibble)
library(stringr)
library(magrittr)
library(purrr)
library(pillar)
library(readr)
library(purrr)

library(tydygraphs)

library(dygraphs)

library(sparkline)
library(plotly)

ROOTPATH<- fs::path_abs(params$ROOTPATH)

( ROOTPATH )
```


```{r, label='masic-log-util'}
LOGFILE <- "MASIC.log"
log_variable <- function(variable_name, variable_value) {
  summary_value <- create_summary(variable_value)
  sink(LOGFILE, append = TRUE)
  cat("Logged Variables\n")
  # print(logged_variables)
  print(variable_name)
  print(summary_value)
  cat("\n")
  sink()
  # data.frame(Name = variable_name, Value = toString(variable_value), stringsAsFactors = FALSE)
  # c(variable_name, summary_value) %>% map(message)
  return(variable_value)


}

data_frame <- tibble
create_summary <- function(input) {
  if (is.data.frame(input)) {
    .x <- pillar::glimpse(input)
    .log <- list(names(input), input)
    return(.log)
  } else if (is.list(input)) {
    if (length(input) == 0) {
      return("Empty list")
    }
    input_summary <- lapply(input, create_summary) # recursive apply the next level of `input` to self
    names(input_summary) <- names(input)
    return(input_summary)
  } else {
    #return(summary(input))
    return(input)
  }
}
log_variable('ROOTPATH', list(name=ROOTPATH))

```

```{r label="func def for summarizing continuous data"}
# in the future, likely to replace with tools provided in: https://github.com/easystats/report
# and/or https://github.com/ddsjoberg/gtsummary
calc_stat_summary <- function(.x, .var) {
    .x %>%
        summarize(
            mean = mean({{ .var }}, na.rm=T),
            sd = sd({{ .var }}, na.rm = T),
            median = median({{ .var }}, na.rm=T),
            max = max({{ .var }}, na.rm=T),
            min = min({{ .var }}, na.rm=T),
            .groups = "keep"
        )
}

```
  
  
```{r}

NUM_ROWS <- 300

TEST_DATA_COLUMNS <- list()

COLS_SICstats <- c(
  "Dataset",
  "ParentIonIndex",
  "MZ",
  "SurveyScanNumber",
  "FragScanNumber",
  "OptimalPeakApexScanNumber",
  "PeakApexOverrideParentIonIndex",
  "CustomSICPeak",
  "PeakScanStart",
  "PeakScanEnd",
  "PeakScanMaxIntensity",
  "PeakMaxIntensity",
  "PeakSignalToNoiseRatio",
  "FWHMInScans",
  "PeakArea",
  "ParentIonIntensity",
  "PeakBaselineNoiseLevel",
  "PeakBaselineNoiseStDev",
  "PeakBaselinePointsUsed",
  "StatMomentsArea",
  "CenterOfMassScan",
  "PeakStDev",
  "PeakSkew",
  "PeakKSStat",
  "StatMomentsDataCountUsed",
  "InterferenceScore"
)
TEST_DATA_COLUMNS %<>% append(list(a_COLS_SICstats = COLS_SICstats))
TEST_DATA_COLUMNS %<>% append(list(b_COLS_SICstats = COLS_SICstats))

COLS_REPORTER_IONS <- c(
  "Dataset",
  "ScanNumber",
  "Collision",
  "Mode",
  "ParentIonMZ",
  "BasePeakIntensity",
  "BasePeakMZ",
  "ReporterIonIntensityMax",
  "Ion_126.128",
  "Ion_127.125",
  "Ion_127.131",
  "Ion_128.128",
  "Ion_128.134",
  "Ion_129.131",
  "Ion_129.138",
  "Ion_130.135",
  "Ion_130.141",
  "Ion_131.138",
  "Ion_131.144",
  "Weighted Avg Pct Intensity Correction"
)
TEST_DATA_COLUMNS %<>% append(list(COLS_REPORTER_IONS1 = COLS_REPORTER_IONS))
TEST_DATA_COLUMNS %<>% append(list(COLS_REPORTER_IONS2 = COLS_REPORTER_IONS))

make_test_data <- function(column_names, num_rows=300) {
  # map_dfc because we want to return a dataframe based on the column names we are feeding in
  # runif <- random draw uniform distribution
  .uid <- format(Sys.time(), "%Y%m%d%H%M%OS6") 

  map_dfc(
    column_names,
    # ~  = inline expression
    # !! = eval expression
    # .x = a column name
    # := = assignment
    ~ tibble(!!.x := runif(num_rows))
  ) %>%  mutate(id=.uid) %>%  # this is for SICstats only now.
    mutate(SurveyScanNumber = 1:num_rows,
           ParentIonIndex = 1:num_rows,
           MZ = (rbeta(num_rows, 3, 6) * 1000 ) + 200,
           ParentIonIntensity = rexp(num_rows ) * 10000 ,
           )
}

( make_test_data(list("a", "b", "c"), num_rows = 10) ) # test


.test <- list(
  list('a', 'b', 'c'),
  list('a', 'b', 'c')
) %>% map(~make_test_data(.,num_rows = 10))

.test <- list(
  
  list('a', 'b', 'c'),
  list('a', 'b', 'c')
) %>% map_dfr(~make_test_data(.,num_rows = 2))
( .test )


# not working
#.test <- replicate(
#  list('a', 'b', 'c'), n=3,
#) #%>% map_dfr(~make_test_data(.,num_rows = 2))
#( .test )

.test %>% count(id)
( make_test_data(list("a", "b", "c"), num_rows = 10) ) # test

```
# make data
  


```{r label=masic.load}
log_variable("ROOTPATH", ROOTPATH)
SIC_MASIC_FILES <- fs::dir_ls(
  path = ROOTPATH,
  recurse = TRUE,
  regexp = ".*SICstats.txt"
 )


SCANSTAT_MASIC_FILES <- fs::dir_ls(
  path = ROOTPATH,
  recurse = TRUE,
  regexp = ".ScanStats.txt"
  #regexp = ".*ScanStats.txt"
 )
log_variable("SCANSTAT_MASIC_FILES", SCANSTAT_MASIC_FILES)
cat(SCANSTAT_MASIC_FILES)

REPORTERION_MASIC_FILES <- fs::dir_ls(
  path = ROOTPATH,
  recurse = TRUE,
  regexp = ".ReporterIon.txt"
 )


( SIC_MASIC_FILES )

df <- SIC_MASIC_FILES %>%  map_df(~ vroom(.x, n_max = Inf) %>% mutate(id = fs::path_file(.x)))
scanstats <- SCANSTAT_MASIC_FILES %>%  map_df(~ vroom(.x, n_max = Inf) %>% mutate(id = fs::path_file(.x)))
#df <- SCANSTAT_MASIC_FILES %>%  map_df(~ vroom(.x, n_max = 300) %>% mutate(id = fs::path_file(.x)))
# one big dataframe with file id as one column

if (df %>% length() == 0)
  {
    #( make_test_data(list("a", "b", "c"), num_rows = 10) ) # test
    # make fake data
    .df <- list(
      COLS_SICstats,
      COLS_SICstats,
      COLS_SICstats
             ) %>% 
      map_df(
        ~ make_test_data(., num_rows = 300)
      )
    
#TEST_DATA_COLUMNS %<>% append(list(a_COLS_SICstats = COLS_SICstats))
#TEST_DATA_COLUMNS %<>% append(list(b_COLS_SICstats = COLS_SICstats))
    
    
  df <- .df
  }

```

```{r, label=MASIC-scanstats}
.negsel <- c(
 "Dataset",
 "ParentIonIndex",
 "SurveyScanNumber",
 "FragScanNumber",
 "OptimalPeakApexScanNumber",
 "PeakApexOverrideParentIonIndex",
 "CustomSICPeak",
 "PeakScanStart",
 "PeakScanEnd"
             )
#scanstats %>% 
#  select(-any_of(.negsel)) %>% 
#  modelsummary::datasummary_skim()
```



```{r}
# df %>% 
#   group_by(id) %>% 
#     calc_stat_summary(
#       ParentIonIntensity
#       )


```


## MS1
```{r, label='masic-scanstats-sparkline-MS1-total'}
.sparkline <- scanstats %>% 
    filter(ScanType==1) %>% 
    group_by(id) %>%
    arrange(ScanNumber) %>%
  summarise(TotalIonIntensity=
              spk_chr(
                TotalIonIntensity,
                width=280,
                #height=10,
                chartRangeMin=0
                #xAxis = list(ticks = 1:length(ParentIonIntensity),
                #              labels = seq_along(ParentIonIntensity))
              ) 
            ) %>% 
  formattable::formattable(align = c("l", "r"),
       value = formattable::formatter(
        style = formattable::style(
           display = "inline-block",  
           `padding-left` = '50px',
           `padding-right` = '10px'
        )
       )
  ) %>% 
  formattable::as.htmlwidget() %>% # this step is important
  spk_add_deps()


.sparkline


```
## MS2
```{r, label='masic-scanstats-sparkline-MS2-total'}
.sparkline <- scanstats %>% 
    filter(ScanType==2) %>% 
    group_by(id) %>%
    arrange(ScanNumber) %>%
  summarise(TotalIonIntensity=
              spk_chr(
                TotalIonIntensity,
                width=280,
                #height=10,
                chartRangeMin=0
                #xAxis = list(ticks = 1:length(ParentIonIntensity),
                #              labels = seq_along(ParentIonIntensity))
              ) 
            ) %>% 
  formattable::formattable(align = c("l", "r"),
       value = formattable::formatter(
        style = formattable::style(
           display = "inline-block",  
           `padding-left` = '50px',
           `padding-right` = '10px'
        )
       )
  ) %>% 
  formattable::as.htmlwidget() %>% # this step is important
  spk_add_deps()


.sparkline


```

```{r, label='masic-plotly-plotlen', eval=F}
#plot(.n, .n+.n*(1-.n/(.n+2)))

#.n <- 1:30
#.plotlength <- 4 + ( 
#  .n * ( 1 - .n/(.n + 20)  ) )
#plot(.n, .plotlength)


# .n <-  scanstats %>% pull(id) %>% n_distinct() 
# .plotlength <- 4 + (  .n * ( 1 - .n/(.n + 20)  ) )
```


## MS - plotly { .tabset }
```{r, label='masic-scanstats-plotly', eval=T}
.n <-  scanstats %>% pull(id) %>% n_distinct() 
.plotlength <- 4 + (  .n * ( 1 - .n/(.n + 20)  ) )


# p <- .data %>%
#   plot_ly(x = ~ScanTime, y = ~TotalIonIntensity, type = "scatter", mode = "lines", color = ~factor(id)) %>%
#   layout(title = "Interactive Line Chart with Zooming",
#          xaxis = list(title = "Parent Ion Index"),
#          yaxis = list(title = "Parent Ion Intensity"),
#          dragmode = "zoom") # Enable zooming
# p
```
### MS1

```{r label='masic-scanstats-plotly-ms1', fig.width=.plotlength}

.data <- scanstats %>% 
    filter(ScanType==1) %>% 
    group_by(id) %>%
    arrange(ScanNumber)
p <- ggplot(.data, aes(x = ScanTime, y = TotalIonIntensity, group = id)) +
  geom_line() +
  facet_wrap(~ id, ncol = 1) +
  theme_minimal() +
  labs(
    title = "ScanStats MS1 TotalIonIntensity",
    x = "ScanTime",
    y = "TotalIonIntensity"
      )

# Convert the ggplot chart to an interactive plotly chart
interactive_p <- ggplotly(p)

# Display the interactive chart
interactive_p
```

### MS2
```{r label='masic-scanstats-plotly-ms2', fig.width=.plotlength}

.data <- scanstats %>% 
    filter(ScanType==2) %>% 
    group_by(id) %>%
    arrange(ScanNumber)
p <- ggplot(.data, aes(x = ScanTime, y = TotalIonIntensity, group = id)) +
  geom_line() +
  facet_wrap(~ id, ncol = 1) +
  theme_minimal() +
  labs(
    title = "ScanStats MS2 TotalIonIntensity",
    #title = " Interactive Line Charts",
     x = "ScanTime",
     y = "TotalIonIntensity"
       )

# Convert the ggplot chart to an interactive plotly chart
interactive_p <- ggplotly(p)

# Display the interactive chart
interactive_p
```


```{r, label='masic-sparkline'}
#cat(colnames(df))
#.sparkline <- df %>% group_by(id) %>% arrange(ParentIonIndex) %>%  summarise(ParentIonIntensity=spk_chr(ParentIonIntensity, width=600, height=100))

#if (!("ScanType" %in% colnames(df))

#.sparkline <- df %>% filter(ScanType==1) %>%  
.sparkline <- df %>%  
  group_by(id) %>%
  arrange(ParentIonIndex) %>%
  summarise(ParentIonIntensity=
              spk_chr(
                ParentIonIntensity,
                width=280,
                #height=10,
                chartRangeMin=0
                #xAxis = list(ticks = 1:length(ParentIonIntensity),
                #              labels = seq_along(ParentIonIntensity))
              ) 
            ) %>% 
  formattable::formattable(align = c("l", "r"),
       value = formattable::formatter(
        style = formattable::style(
           display = "inline-block",  
           `padding-left` = '50px',
           `padding-right` = '10px'
        )
       )
  ) %>% 
  formattable::as.htmlwidget() %>% # this step is important
  spk_add_deps()

.sparkline 
```


```{r, MASIC-mz}

# ggpubr::ggline(df,
#                   x="ParentIonIndex",
#                   y="MZ",
#                facet.by = 'id'
#                #group="id"
#                   )

```

