---
title: "PCA"
author: "AlexSaltman"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn # pygments, kate, monochrome, zenburn
    includes:
      #in_header: header.html 
params:
  use_paramfile:
    value:
      TRUE
  paramfile:
    value:
      NULL  
  color:
    value: Extract_Genotype
  marker:
    value: Extract_Treatment
  title:
    value:
      PCA
  center:
    value:
      TRUE
  scale:
    value:
      TRUE
  annotate:
    value:
      TRUE
  encircle:
    value:
      FALSE
  colkey:
    value: NULL 
    description:
        "Vector of name-value pairs relating to value passed to 'col', e.g., c(A='forestgreen', B='gold')."
      
  logging:
    value:
      message: FALSE
      warning: FALSE
---


```{r, label=pca.setup, include=F}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cmapR))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(PCAtools))
# library(PCAtools)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = params$logging$MESSAGE)
knitr::opts_chunk$set(warning = params$logging$WARNING)
source("funcs.R")
get_param <- function(param){
  if(is.list(param) && "value" %in% names(param)){
    return(param$value)
  } else{
    return(param)
  }
}

.f <- get_param(params$paramfile)
if (!is.null(.f) && fs::file_exists(.f) && params$use_paramfile == TRUE) {
  subparams <- yaml::yaml.load_file(.f)
  cat(paste("loading", .f))
  #params <- modifyList(params, local_params)
} else{
  subparams <- params
}
```


```{r, label=pca.title, include=T}
subparams$title
```


```{r, label=pca.environment, include=F}
method <- subparams$method
# check if .gct obj is in environment
if (!exists("gct")) {
  set.seed(369)
  .mat <- matrix(runif(1000), nrow = 100, ncol = 20)
  .rids <- seq(1, dim(.mat)[1]) %>% as.character()
  .cids <- seq(1, dim(.mat)[2]) %>% as.character()
  .rdesc <- data.frame(
    rdesc=.cids,
    id = .rids
  )
  .cdesc <- tibble::tibble(
    id = .cids,
    metavar1 = sample(letters[1:10], 20, replace = T) %>% as.factor(),
    metavar2 = sample(letters[1:5], 20, replace = T) %>% as.factor(),
  )
  gct <- cmapR::GCT(mat = .mat, rid = .rids, cid = .cids, cdesc = .cdesc, rdesc = .rdesc)
  subparams$color <- "metavar1"
  subparams$marker <- "metavar2"
  # gct = new(cmgct)
} else {
  # If 'gct' exists, just use the existing one
  cat("Using existing 'gct'.\n")
}
```

```{r, label=pca.gct-show-cdesc}
gct@cdesc %>% head
```

```{r, label=pca.gct-show-mat}
gct@mat %>% head()
```



```{r, label=pca.begin}
# from https://www.bioconductor.org/packages/release/bioc/vignettes/PCAtools/inst/doc/PCAtools.html#conduct-principal-component-analysis-pca
# .forpca <- mat(gct)

# rows are genes
# columns are samples
# id.x is gene
# id.y is sample
# .center <- TRUE
# .scale <- TRUE
.center <- subparams$center
.scale <- subparams$scale
# (.center)
# (.scale)
.rescaled_gct_mat <- gct %>%
  cmapR::melt_gct() %>%
  group_by(id.x) %>%
  mutate(
    value = scale(
      value, # expression value after cmapR::melt_gct
      center = !!.center,
      scale = !!.scale
    )
  ) %>% 
  ungroup
# drop anything that has a value of NaN. There probably should not be any Nans, but even if there are we will not deal with that here.
.rescaled_gct_mat %>% filter(is.na(value))  # are there any?
#
.rescaled_gct_mat[ is.na(.rescaled_gct_mat$value), 'value' ] <- 0
#.rescaled_gct_mat %<>% filter(!is.na(value))
.forpca <- .rescaled_gct_mat %>%
  mutate(id.x = as.character(id.x)) %>%
  pivot_wider(
    values_from = value,
    id_cols = id.x,
    names_from = id.y
  ) %>% ungroup()
.rownames <- .forpca$id.x
.forpca <- .forpca %>% select(-id.x) %>% as.data.frame
rownames(.forpca) <- .rownames
  
.forpca <- .forpca[, gct@cid] # put back in order
  #tibble::column_to_rownames(var="id.x")
  # need the rownames to be set to the geneids
  # this does it 

  #%>% as.data.frame()
  
  # make to gene symbols in the rdesc slot
# if (!(is.null(gct@rdesc))){
#   if ("SiteName" %in% colnames(gct@rdesc))
#     .rdesc <- paste(gct@rdesc$SiteName, gct@rdesc$id)
#   else if ("GeneSymbol" %in% colnames(gct@rdesc))
#     .rdesc <- paste(gct@rdesc$id, gct@rdesc$GeneSymbol)  #ensure always is unique
#   else
#     .rdesc <- rownames(.forpca)
#    
#   rownames(.forpca) <- .rdesc 
#   # this is not working
#    #unite("concatenated_column", everything(), sep = "-") %>% 
#    #jpull(concatenated_column)
# }
# browser()
# cat(.forpca)
#print(.forpca$id.x)
#print(rownames(.forpca))

#.rownames <- .forpca$id.x %>% as.character() # just to be clear
#rownames(.forpca) <- .rownames

# .forpca %<>%

# .forpca %<>% subset(select=c(-id.x))
# (.rownames<-apply(head(.gct@rdesc), 1, paste, collapse = NULL))
# cmapR::
# .forpca
# .rownames<-apply(gct@rdesc, 1, paste, collapse = " ")
# .gct@rdesc %>% head %>% rowwise() %>% mutate(x=str_c(everything(  )))
# .gct@rdesc[.gct@rdesc == rownames(.forpca)]
.metadata <- gct@cdesc %>% as.data.frame()
rownames(.metadata)

# print('pca')
.pcaobj <- PCAtools::pca(
  .forpca,
  metadata = gct@cdesc %>% as.data.frame() # no tibbles allowed
)
```
# PCA Results

## elbow 

```{r, label=pca.elbow}
.elbow <- PCAtools::findElbowPoint(.pcaobj$variance)
.p <- screeplot(.pcaobj,
  components = 1:10,
  axisLabSize = 18,
  titleLabSize = 22,
  vline = .elbow
) 
#

.p +
  geom_label(aes(
    x = .elbow - 1,
    y = 50,
    label = "Elbow method", vjust = -1, size = 8
  ))

```

## PCA Results { .tabset }
```{r, label=pca.biplot, fig.width=7, fig.height=7}
# https://www.bioconductor.org/packages/release/bioc/vignettes/PCAtools/inst/doc/PCAtools.html#conduct-principal-component-analysis-pca
#.color_by <- "SampleType"
#  get rom input
if ("metavar1" %in% colnames(gct@cdesc)) .color_by <- "metavar1"
# if ("avg.silhouette.width" %in% colnames(clusterings)) .var <- 'avg.silhouette.width'
#colby <- params$color
#shape <- params$marker
mybiplot <- function(.pcaobj, x="PC1", y="PCA2", color = NULL, marker = NULL, legend = T, ...) {
  #
  .do_legend <- ifelse(legend==T, "right", "none")
  print(.do_legend)
  .res <- biplot(
    .pcaobj,
    x = x,
    y = y,
    showLoadings = T,
    ntopLoadings = 5,
    sizeLoadingsNames = 2,
    hline = 0,
    vline = 0,
    colby = color,
    shape = marker,
    # colby=colby,
    #shape=shape,
    #colby = NULL,
    # colby="SampleType",
    # shape='OrganSite',
    #shapekey = NULL,
    #ellipse = T,
    legendPosition = .do_legend,
    # ...
  )
  .res
}
color <- subparams$color
marker <- subparams$marker
annotate <- subparams$annotate
mybiplot_partial <- purrr::partial(mybiplot, color=color, marker=marker, annotate=annotate)
 #biplot(.pcaobj, colby="metavar1")
```

### pca.biplot-1-2 

```{r, label=pca.biplot-1-2, fig.width=12, fig.height=10}
color = subparams$color
marker = subparams$marker
mybiplot_partial(
  .pcaobj, x = "PC1", y = "PC2", 
)
# mybiplot(.pcaobj, x = "PC1", y = "PC2", 
#          colby = color,
#          shape = marker,
#          legend = T
#          )
```

### pca.biplot-1-3 

```{r, label=pca-biplot-1-3, fig.width=12, fig.height=10}
# mybiplot(.pcaobj, x = "PC1", y = "PC3",
#          colby = colby,
#          legend=T)
mybiplot_partial(
  .pcaobj, x = "PC1", y = "PC3", 
)
# biplot(.pca,
#        x="PC1",
#        y="PC2",
#        showLoadings = T,
#        ntopLoadings=5,
#        sizeLoadingsNames = 3,
#        colby="SampleType",
#        #shape='OrganSite',
#        shapekey=NULL,
#        ellipse=T,
#        legendPosition = "top"
#        )
```

### pca.biplot-2-3 

```{r, label=pca-biplot-2-3, fig.width=12, fig.height=10}

mybiplot_partial(
  .pcaobj, x = "PC2", y = "PC3", 
)
# mybiplot(.pcaobj, x = "PC2", y = "PC3",
#          colby = colby,
#          legend=T)
# .pca %>% airsplot()
```
```{r, label=pca-loadings1,  fig.width=12, fig.height=10}
# myplotloadings <- function(.pcaobj, ...) {
#   plotloadings(
#     .pcaobj,
#     rangeRetain = .01,
#     components = 10,
#     ...
#   )
# }
# .pcaobj %>% myplotloadings(labSize = 3)
```

### {-}




## PCA loadings { .tabset }
### Loading relative
```{r, label=pca.myplotloadings.rel, fig.width=7, fig.height=7, echo=F}

components <- seq(5)
Nloadings <- 10
pca_loadings <-  .pcaobj$loadings[, components]
loadings_long <- as.vector(as.matrix(pca_loadings[,components]))  # select 5
loadings_abs_sorted <- sort(abs(loadings_long), decreasing = FALSE)
rangeRetain_value <- loadings_abs_sorted[Nloadings]

  plotloadings(.pcaobj,
               components = seq(5),
    rangeRetain = rangeRetain_value,
    labSize = 4.0,
    title = 'Loadings plot',
    subtitle = 'PC1, PC2, PC3, PC4, PC5',
    caption = 'Top 1% variables',
    shape = 24,
    #col = c('limegreen', 'black', 'red3'),
    drawConnectors = TRUE)
#.pcaobj %>% myplotloadings(labSize = 3, absolute = F)
```

### Loadings absolute
```{r, label=pca.myplotloadings.abs, fig.width=7, fig.height=7, echo=F, include=F, eval=F}

components <- seq(5)
Nloadings <- 10
pca_loadings <-  .pcaobj$loadings[, components]
loadings_long <- as.vector(as.matrix(pca_loadings[,components]))  # select 5
loadings_abs_sorted <- sort(abs(loadings_long), decreasing = FALSE)
rangeRetain_value <- loadings_abs_sorted[Nloadings]

  plotloadings(.pcaobj,
               components = components,
    rangeRetain = rangeRetain_value,
    labSize = 4.0,
    title = 'Loadings plot',
    subtitle = 'PC1, PC2, PC3, PC4, PC5',
    caption = 'Top 1% variables',
    shape = 24,
    absolute=TRUE,
    #col = c('limegreen', 'black', 'red3'),
    drawConnectors = TRUE)
#.pcaobj %>% myplotloadings(labSize = 3, absolute = F)
```
##  break

## Loadings one at a time { .tabset }

### PCA1
```{r, label='pca-loading1', eval=T, include=T, fig.width=10, fig.height=8}
# this could be made dynamically
component <- 1
Nloadings <- 10
pca_loadings <-  .pcaobj$loadings[, component]
loadings_long <- pca_loadings # only one
#loadings_long <- as.vector(as.matrix(pca_loadings[,components]))  # select 5
loadings_abs_sorted <- sort(abs(loadings_long), decreasing = FALSE)
rangeRetain_value <- loadings_abs_sorted[Nloadings]

plotloadings(.pcaobj,
   components = getComponents(.pcaobj, c(component)),
   rangeRetain = rangeRetain_value,
   absolute = TRUE,
   col = c('black', 'pink', 'red4'),
   drawConnectors = TRUE, labSize = 4) + coord_flip()
```
### PCA2
```{r, label='pca-loading2', eval=T, include=T}
# this could be made dynamically
component <- 2
Nloadings <- 10
pca_loadings <-  .pcaobj$loadings[, component]
loadings_long <- pca_loadings # only one
#loadings_long <- as.vector(as.matrix(pca_loadings[,components]))  # select 5
loadings_abs_sorted <- sort(abs(loadings_long), decreasing = FALSE)
rangeRetain_value <- loadings_abs_sorted[Nloadings]

plotloadings(.pcaobj,
   components = getComponents(.pcaobj, c(component)),
   rangeRetain = rangeRetain_value,
   absolute = FALSE,
   col = c('black', 'pink', 'red4'),
   drawConnectors = TRUE, labSize = 4) + coord_flip()
```

### PCA3
```{r, label='pca-loading3', eval=T, include=T}
# this could be made dynamically
component <- 3
Nloadings <- 10
pca_loadings <-  .pcaobj$loadings[, component]
loadings_long <- pca_loadings # only one
#loadings_long <- as.vector(as.matrix(pca_loadings[,component]))  # select 5
loadings_abs_sorted <- sort(abs(loadings_long), decreasing = FALSE)
rangeRetain_value <- loadings_abs_sorted[Nloadings]

plotloadings(.pcaobj,
   components = getComponents(.pcaobj, c(component)),
   rangeRetain = rangeRetain_value,
   absolute = FALSE,
   col = c('black', 'pink', 'red4'),
   drawConnectors = TRUE, labSize = 4) + coord_flip()
```

## { - }



```{r, label='pca-misc-loadings', eval=F}
# p <- .pcaobj
#  plotloadings(p,
#     components = getComponents(p, c(4,9,3)),
#     rangeRetain = 0.1,
#     labSize = 4.0,
#     absolute = FALSE,
#     title = 'Loadings plot',
#     subtitle = 'Misc PCs',
#     caption = 'Top 10% variables',
#     shape = 23, shapeSizeRange = c(1, 16),
#     col = c('white', 'pink'),
#     drawConnectors = FALSE)
```

###


```{r, label=pca-empty}
# not sure what this means for non-numeric
# .p %>% eigencorplot(
#   metavars = c(
#     "SampleType",
#     "OrganSite",
#     "PDXModel",
#     #"plex"
#   )
# )
```
 
 
 
```{r, pca-toploadings-heatmap, eval=F, include=F}

# library(ComplexHeatmap)
# .negsel <- c("sample", "plex", "recno", "label", "id", "runno", "searchno", "assay", "replicate")
# .column_df <- .gct@cdesc %>% select(-any_of(.negsel))
# 
# recycle_colors <- function(type = "qual", n = 8) {
#   # original_palette <- brewer_pal(palette = palette_name)(min(n, 8))
#   original_palette <- brewer_pal(type = "qual", palette = 2)(min(n, 8))
#   recycled_palette <- rep_len(original_palette, length.out = n)
#   return(recycled_palette)
# }
# #
# # .color_list <- .column_df %>% as.list %>% map( ~ brewer_pal("qual", palette=2)(length(unique(.))) )
# 
# 
# .color_list <- .column_df %>%
#   as.list() %>%
#   map(~ recycle_colors(n = length(unique(.))))
# # fix this maybe if better
# for (col in colnames(.column_df)) {
#   # print(col)
#   # names(.color_list[[col]]) <-  unique(.column_df[[col]])
#   names(.color_list[[col]]) <- unique(.column_df[[col]])
# }
# 
# 
# .top_annotation <- columnAnnotation(
#   df = .column_df %>% as.data.frame(),
#   col = .color_list
#   # col = anno_block(gp = gpar(fill = .color_list$metavar1))
# )

# col = .color_list )

#ComplexHeatmap::Heatmap()
```
 
# params
```{r, label=pca.params}
( subparams )

```

