---
title: "tackle"
author: "AlexSaltman"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn # pygments, kate, monochrome, zenburn
    toc: yes

params:
  routines:
    value:
      cluster: false
      PCA: false
      volcano: false
      GSEA: true
  gct_file:
    value: "MSPC000769_TMT11_prof_Config_data_gct_all_1.0more_nonzero_parametricBatch_plex_noCov_normtype_median_n99x10955.gct"
    description: if specified, will use this gct file
  ROOTPATH: 
    #value: "`normalizePath(dirname('.'))`"
    value: "../.."
    description: supposed to be dynamic
  paramfile:
    value: ""
  cluster_methods:
    value: [kmeans]
  pca:
    value:
      color:
        value:
      marker:
        value:
      annotate:
        value: true
      center:
        value: true
      scale: 
        value:
          true
  cluster:
    value:
      cluster_rows:
        value: true
        description: "cluster the rows"
      cluster_columns:
        value: true
      cluster_row_slices:
        value: true
      cluster_col_slices:
        value: true
      clustering_distance_rows:
        value: euclidean
      clustering_method_rows:
        value: ward.d2
      legend_include:
        value: 
        description: "metadata variables to include"
      legend_exclude:
        value:
        description: "metadata variables to exclude"
  logging:
    value:
      message: TRUE
      warning: TRUE
      quiet: TRUE
end:
# 
  
---

```{r tackle-setup, include=FALSE}
suppressPackageStartupMessages(library(tidymodels))
library(modelsummary)

suppressPackageStartupMessages(library(cmapR))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(gt))
suppressPackageStartupMessages(library(fs))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(tibble))
# let's pick one
library(DT)
# library(reactable)
#
knitr::opts_chunk$set(echo = TRUE)
```

```{r, label=tackle-params-check, eval=T, message=T, warning=T}
print(params)
print(params$routines)
cat(params$routines %>% as.character())
#browser()
if (is.null(params$routines)){
  knitr::knit_exit()
  
}

```

logging options
```{r label=tackle-logging}
# MESSAGE<-F
# WARNING<-F
knitr::opts_chunk$set(message = params$logging$message, warning = params$logging$warning)

LOGFILE <- "MASIC.log"
log_variable <- function(variable_name, variable_value) {
  summary_value <- create_summary(variable_value)
  sink(LOGFILE, append = TRUE)
  cat("Logged Variables\n")
  # print(logged_variables)
  print(variable_name)
  print(summary_value)
  cat("\n")
  sink()
  # data.frame(Name = variable_name, Value = toString(variable_value), stringsAsFactors = FALSE)
  # c(variable_name, summary_value) %>% map(message)
  return(variable_value)


}

data_frame <- tibble
create_summary <- function(input) {
  if (is.data.frame(input)) {
    .x <- pillar::glimpse(input)
    .log <- list(names(input), input)
    return(.log)
  } else if (is.list(input)) {
    if (length(input) == 0) {
      return("Empty list")
    }
    input_summary <- lapply(input, create_summary) # recursive apply the next level of `input` to self
    names(input_summary) <- names(input)
    return(input_summary)
  } else {
    #return(summary(input))
    return(input)
  }
}



```

tackle load

```{r label=tackle-load}
#ROOTPATH <- params$ROOTPATH
ROOTPATH<- fs::path_abs(params$ROOTPATH)


if (!is.null(params$gct_file)){
  
  gct <- cmapR::parse_gctx(params$gct_file)
  
} else {

  gct_files <- fs::dir_ls(
    path = ROOTPATH,
    recurse = TRUE,
    regexp = ".gct"
  )
  stringr::str_c("Found", gct_files) %>% cat()
  # ( gct_files )
  
  gcts <- gct_files %>%
    purrr::map(
      # ~cmapR::parse_gctx()
      ~ cmapR::parse_gctx(.x) # , rid=1:100)
    )
  gct <- gcts[[1]]

}
metadata <- gct@cdesc %>% as.data.frame() # no tibbles allowed
# DEBUGING

# print(gcts)
```

tackle funcs
```{r, label=tackle-funcs}

myzscore <- function(value, minval = NA, remask = TRUE) {
  mask <- is.na(value)
  if (is.na(minval)) minval <- min(value, na.rm = TRUE)
  value[is.na(value)] <- minval
  out <- scale(value)
  if (remask == TRUE) {
    out[mask] <- NA
  }
  return(out)
}
dist_no_na <- function(mat) {
  mat[is.na(mat)] <- min(mat, na.rm = TRUE)
  edist <- dist(mat)
  return(edist)
}
make_new_gct <- function(gct, mat) {
  # make a new gct object with the same metadata as the original
  # this only works if mat is same dimension as original mat
  new("GCT",
    mat = mat,
    rid = gct@rid,
    cid = gct@cid,
    rdesc = gct@rdesc,
    cdesc = gct@cdesc,
  )
}
```


# results 
maybe `{.tabset} is a feature we may use later`

## metadata

```{r, label='tackle-cdesc-viz', eval=T}
gct@cdesc %>%
  select(recno, runno, searchno, label, everything()) %>%
  modelsummary::datasummary_skim()
```
```{r, label='tackle-cdesc-table', eval=T}
# .gct <- gcts[[1]]
# .gct@cdesc

# gct@cdesc %>%
#   select(recno, runno, searchno, label, everything()) %>%
#   gt::gt(
#   caption="metadata"
# )

.table <- gct@cdesc %>%
  select(recno, runno, searchno, label, everything()) %>%
  DT::datatable(
    options <- list(
      style = c(
        "compact",
        "stripe"
      )
    )
  )
.table
```






## metrics

## cluster


render cluster.Rmd
```{r, label=tackle-cluster, message=T, warning=T, results='show', eval=params$routines$cluster}

.params <- params$cluster

# .params$method <- "kmeans"

render_cluster_report <- function(method = "kmeans") {
  .output_file_name <- paste0("cluster_", "method_", method, ".html")

  # log_fh <- file("render_log.txt", open = "a")
  # sink(log_fh, type = "message")


  rmarkdown::render("cluster.Rmd",
    output_file = .output_file_name,
    params = list(method = method),
    quiet = T

    # params=.params,
    # envir = globalenv(),
    # envir = new_env
    # documentation=1,
  )
  return(.output_file_name)

  # not sure if this is exactly how to get the path right
  # c(params$ROOTPATH, .output_file_name) %>% fs::path_join() %>% fs::path_abs()
  # sink(type = "message")
  # close(log_fh)
}
.out <- render_cluster_report(method = "kmeans")

# htmltools::includeHTML(.out)
# .out %>%  htmltools::includeHTML()
# TODO: loop through all the methods
#.params <- params$cluster$
# .out <- render_cluster_report(method='pam')
# htmltools::includeHTML(.out)

# htmltools::includeHTML("cluster1.html")
```

```{r tackle-cluster-report-sep-page, echo=T, results="asis", eval=params$routines$cluster}
.html <- cat(paste0("[", .out, "](", .out, ")"), "\n\n")
( .html )
## {-}
```




render PCA.Rmd
```{r, label=tackle-pca, message=T, warning=T, results='show', eval=params$routines$PCA}

.params <- params$PCA

# .params$method <- "kmeans"

render_pca_report <- function(center = T, scale = F) {
  .output_file_name <- paste0("PCA", "center_", center, "scale_", scale, ".html")
  rmarkdown::render("PCA.Rmd",
    output_file = .output_file_name,
    quiet = T,
    params = list(
      center = center,
      scale = scale
    )
    # params=.params,
    # envir = globalenv(),
    # envir = new_env
    # documentation=1,
  )
  return(.output_file_name)
  # c(params$ROOTPATH, .output_file_name) %>% fs::path_join() %>% fs::path_abs()
}
```

```{r, echo=T, eval=params$routines$PCA}
# TODO: allow customization
.center <- T
.scale <- T
.out <- render_pca_report(center = .center, scale = T)
# html
# .html <- cat(paste0("[", .out, "](", .out, ")"), "\n\n")
# print(.html)

# htmltools::includeHTML(.out)
```
LINK
```{r pca-report-1-html-pagetest, echo=F, results="asis", eval=params$routines$PCA}
.html <- cat(paste0("[", .out, "](", .out, ")"), "\n\n")
# print(.html)
## {-}
```
next

```{r pca-report-2, eval=params$routines$PCA}
.out <- render_pca_report(center = .center, scale = F)
# htmltools::includeHTML(.out)
```

```{r, pca-report-2-html-pagetest, echo=F, results="asis", eval=params$routines$PCA}
.html <- cat(paste0("[", .out, "](", .out, ")"), "\n\n")
## {-}
```





## GSEA

```{r, tackle-gsea-render, eval=params$routines$GSEA}
.gsea_params <- params$gsea
.out <- rmarkdown::render("GSEA.Rmd",
  #output_file = .output_file_name,
  quiet = F,
  params = .gsea_params,
  envir = new.env(),
  # params=.params,
  # envir = globalenv(),
  # envir = new_env
  # documentation=1,
)
.out <- path_rel(.out) # make it relative so file can be found by browser
# return(.output_file_name)

(params$routines )
# c(params$ROOTPATH, .output_file_name) %>% fs::path_join() %>% fs::path_abs()

```

```{r, tackle-gsea-report, echo=F, results="asis", eval=params$routines$GSEA}
.html <- cat(paste0("[", .out, "](", .out, ")"), "\n\n")
## {-}
(.html)

```
## YFG

```{r, label=tackle-onegene, eval=F, fig.width=10, fig.height=7}
.sel <- gct %>%
  melt_gct() %>%
  filter(id.x == "928") %>%
  mutate(id.y = factor(id.y, levels = gct@cid, ordered = T))

.gene <- .sel$rdesc %>% unique()
.color <- ifelse(!is.null(params$color) == T, params$color, 'black')
.sel %>%
  ggpubr::ggbarplot(
    x = "id.y",
    y = "value",
    title = .gene,
    # color = case(params$color, F),
    color = .color
  ) %>%
  ggpar(x.text.angle = 90)


.sel %>% DT::datatable()
# .sel
```



